#include<stdio.h>
#include <time.h>
#include <stdlib.h>
#include <stdbool.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>

struct PHEROMONE{
	int seed; /*the pheromone seed generated by Alice and Bob*/
	bool alice; /* true iff the pheromone from Alice was received*/
	bool bob; /*true iff the pheromone from Bob was received*/
	int fees[2]; /*fees[0]: remaining fees from Alice, fees[1]: remaining fees from Bob*/
	int counter[2]; /*counter[0]: counter from Alice, counter[1]: counter from Bob*/
	int sender[2]; /*sender[0]: sender of P(0), sender[1]: sender of P(1)*/
	struct PHEROMONE *left_child;
	struct PHEROMONE *right_child;
	int height;
};

struct PHEROMONE_MESSAGE{  /* information to be forwarded to the next node*/
	bool origin; /*Alice (0) or Bob (1)*/
	int seed;
	int counter;
	int fees;
	int amount;
	time_t timestamp;
	};

struct PHEROMONE *PheromoneTree=NULL;
